### PR TITLE
Sumcoins own Branch to core for further dev

### PR DESCRIPTION
**Pull request by sumcoinlabs**

### CODE REVIEW

**Comment by noxonsu** [comment]
- [ ] remove packages-lock.json 
- [ ] remove  docs/SumSwap.html

**Comment by 5053s** [comment]
@noxonsu Requested changes complete

**Comment by sumcoinlabs** [comment]
hi @noxonsu do any issues need attention before merge?

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/pull/2747 merged and deployed

**Comment by noxonsu** [comment]
you can find some examples for futher development here https://github.com/swaponline/MultiCurrencyWallet/pull/2132/files

**Pull request merged**
